export const ACTION_TYPES = {
    CLOSE_FACETS_MENU: 'CLOSE_FACETS_MENU',
    CLOSE_MAIN_MENU: 'CLOSE_MAIN_MENU',
    FETCH_ALL_BRANDS: 'FETCH_ALL_BRANDS',
    FETCH_PLP_RESULTS: 'FETCH_PLP_RESULTS',
    OPEN_FACETS_MENU: 'OPEN_FACETS_MENU',
    OPEN_MAIN_MENU: 'OPEN_MAIN_MENU'
}